# Generated by Django 4.1.2 on 2023-03-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_pic',
            new_name='blog_pic',
        ),
    ]
